---
title: "Computational Musicology Portfolio"
author: "Sebastiaan Dijkstra"
date: '2022-02-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(dplyr)
library(spotifyr)
library(tidyverse)
library(knitr)
library(lubridate)
library(ggplot2)
```

```{r}
kanye <- get_artist_audio_features("kanye west")
# remove non-deluxe album versions to remove duplicates
kanye <- kanye[!(kanye$album_name == "Watch The Throne" | kanye$album_name == "Donda"), ]
```


### TEST HEADER 1
```{r}
style_progression <- kanye %>%
  group_by(album_name, album_release_year) %>%
  summarize(
    avgDanceability = mean(danceability),
    avgEnergy = mean(energy)
    )

ggplot(style_progression, aes(x=album_release_year)) +
  geom_smooth(aes(y = avgDanceability, color = "Danceability"), se=FALSE) +
  geom_smooth(aes(y = avgEnergy, color = "Energy"), se=FALSE) +
  labs(x = "Year",
       y = "Value",
       color = "Legend",
       title = "Danceability & Energy progression of Kanye West albums through the years."
       )
```

